# #numpy vs Python

In [41]:
l = range(1000)

In [2]:
import numpy as np

In [3]:
d = np.arange(1000)

In [4]:
#for i in range (1,10): r=[x*2 for x in l]

In [5]:
%time for i in range (1,10): r=[x*2 for x in l]

Wall time: 1 ms


In [6]:
%time for i in range (1,10): r=d*2

Wall time: 0 ns


# Multidimensiol Array Object

In [7]:
import numpy as np

In [11]:
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
h=np.ones(((4,4)))
h

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.empty((8,8))

array([[3.23785921e-319, 5.09337610e-316,             nan,
        0.00000000e+000, 4.34330265e-311, 7.90505033e-323,
        3.64588471e-316, 4.47183480e-316],
       [6.81668300e-318, 4.47054351e-316, 0.00000000e+000,
        2.70388927e-316, 0.00000000e+000, 0.00000000e+000,
        4.94065646e-324, 0.00000000e+000],
       [1.50661701e-311, 0.00000000e+000, 6.91770628e-312,
        2.54639495e-312, 1.59089138e-321,             nan,
        2.58883486e-312, 6.36598749e-314],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.0000000

In [14]:
np.array(l)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [29]:
x=np.arange(0,100,5)
x

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [30]:
x.shape

(20,)

In [34]:
f= np.zeros((10,10))
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
f.shape

(10, 10)

In [36]:
f.reshape(2,2,5,5,)

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [37]:
f.dtype

dtype('float64')

In [38]:
f.ndim

2

# Arthematic with Numpy + Vetorized Opertions


In [44]:
import numpy as np

In [46]:
a = np.random.randn((10))

In [47]:
b = np.random.randn((10))

In [48]:
a

array([-0.90706339,  1.84651536,  0.31090681,  0.42046425, -0.77490814,
        0.11233534, -0.19452535, -0.13777898, -2.01712539,  0.09981114])

In [49]:
b

array([ 0.432481  , -0.50632165,  1.37524963, -0.5204394 , -0.17651169,
        0.64127968, -0.33095176, -1.62146805,  0.70094914,  0.63205173])

In [51]:
c=a+b
c

array([-0.47458239,  1.34019371,  1.68615645, -0.09997515, -0.95141983,
        0.75361503, -0.52547712, -1.75924703, -1.31617625,  0.73186288])

In [52]:
a-b

array([-1.33954439,  2.35283701, -1.06434282,  0.94090364, -0.59839646,
       -0.52894434,  0.13642641,  1.48368907, -2.71807452, -0.53224059])

In [53]:
c/2

array([-0.2372912 ,  0.67009686,  0.84307822, -0.04998758, -0.47570992,
        0.37680751, -0.26273856, -0.87962351, -0.65808813,  0.36593144])

In [54]:
b-a

array([ 1.33954439, -2.35283701,  1.06434282, -0.94090364,  0.59839646,
        0.52894434, -0.13642641, -1.48368907,  2.71807452,  0.53224059])

In [55]:
a=b

In [56]:
c-a

array([-0.90706339,  1.84651536,  0.31090681,  0.42046425, -0.77490814,
        0.11233534, -0.19452535, -0.13777898, -2.01712539,  0.09981114])

In [57]:
a[b>0]

array([0.432481  , 1.37524963, 0.64127968, 0.70094914, 0.63205173])

In [58]:
a<0

array([False,  True, False,  True,  True, False,  True,  True, False,
       False])

In [59]:
b<0

array([False,  True, False,  True,  True, False,  True,  True, False,
       False])

# indexing & Slicing

In [66]:
import numpy as np

In [73]:
x=np.array([1,7,5,9,55])
x

array([ 1,  7,  5,  9, 55])

In [74]:
x[4]

55

In [75]:
x[x>5]

array([ 7,  9, 55])

In [76]:
x[[2,4]]

array([ 5, 55])

In [79]:
s = np.random.randn(10,10)
s

array([[ 0.27630252, -0.38891245,  0.10463251,  0.06192539,  0.7680799 ,
        -0.78740456, -0.1449432 ,  0.99088677,  1.5358224 ,  0.4085081 ],
       [ 1.0081063 ,  2.2714753 ,  0.58591182, -0.05910113,  0.1879004 ,
        -0.81527971, -0.59629288, -1.12777249, -1.05218104,  0.08512684],
       [-0.63390364, -0.1698785 ,  1.10512712, -1.76487699, -1.20325638,
        -2.12309472,  0.94698502, -1.09475984, -0.42851934, -0.40452692],
       [-0.28780351, -1.35659535,  0.90282442,  2.28620897,  0.61710048,
         0.69554027,  0.33113098, -2.00169497, -1.01241569, -0.17998398],
       [-0.96387057, -0.00794283, -0.97344261,  0.7109191 ,  1.26030172,
        -0.70272529, -1.03879658,  0.43601493, -0.97565555,  1.94653636],
       [-0.13459454, -1.06424796,  2.06855248, -1.63621484,  2.10126922,
        -0.53932785,  1.05797597,  0.58281991, -0.58937743,  0.55496717],
       [-0.19177757, -0.31923181,  2.02110899,  0.14037997, -1.0355554 ,
        -1.43299849,  0.56775607,  1.26551418

In [80]:
s[1]

array([ 1.0081063 ,  2.2714753 ,  0.58591182, -0.05910113,  0.1879004 ,
       -0.81527971, -0.59629288, -1.12777249, -1.05218104,  0.08512684])

In [81]:
s[0][4]

0.7680799024389728

In [82]:
s[2:9:2]

array([[-0.63390364, -0.1698785 ,  1.10512712, -1.76487699, -1.20325638,
        -2.12309472,  0.94698502, -1.09475984, -0.42851934, -0.40452692],
       [-0.96387057, -0.00794283, -0.97344261,  0.7109191 ,  1.26030172,
        -0.70272529, -1.03879658,  0.43601493, -0.97565555,  1.94653636],
       [-0.19177757, -0.31923181,  2.02110899,  0.14037997, -1.0355554 ,
        -1.43299849,  0.56775607,  1.26551418,  0.63316375,  0.91690267],
       [-1.04087576,  1.36641013,  0.1467573 ,  0.83181057,  1.48434749,
        -1.17207543, -1.80050052, -0.88140663, -0.29100404, -1.61035605]])

In [83]:
s[::4]

array([[ 0.27630252, -0.38891245,  0.10463251,  0.06192539,  0.7680799 ,
        -0.78740456, -0.1449432 ,  0.99088677,  1.5358224 ,  0.4085081 ],
       [-0.96387057, -0.00794283, -0.97344261,  0.7109191 ,  1.26030172,
        -0.70272529, -1.03879658,  0.43601493, -0.97565555,  1.94653636],
       [-1.04087576,  1.36641013,  0.1467573 ,  0.83181057,  1.48434749,
        -1.17207543, -1.80050052, -0.88140663, -0.29100404, -1.61035605]])

In [90]:
s[::,2:5]

array([[ 0.10463251,  0.06192539,  0.7680799 ],
       [ 0.58591182, -0.05910113,  0.1879004 ],
       [ 1.10512712, -1.76487699, -1.20325638],
       [ 0.90282442,  2.28620897,  0.61710048],
       [-0.97344261,  0.7109191 ,  1.26030172],
       [ 2.06855248, -1.63621484,  2.10126922],
       [ 2.02110899,  0.14037997, -1.0355554 ],
       [-0.94374738, -1.05756719, -0.39050658],
       [ 0.1467573 ,  0.83181057,  1.48434749],
       [ 0.33638281, -0.12779053, -0.93466477]])

In [100]:
e=np.ones((5,5))
e

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
e[1:-1,1:-1]=0
e

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [110]:
e[1:-1]=5
e

array([[0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0.]])